name: Build EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pyinstaller
      - run: pyinstaller --noconsole --onefile temp.py
      - uses: actions/upload-artifact@v4
        with:
          name: Otomasyon_Setup
          path: dist/
